### ISSUE TITLE
Resources requests/limits fails to validate when providing the number of CPUs as integers

### ISSUE THREAD

**Issue by thedrow** [garethr/kubeval#22]
I have a Job with the following resources spec for it's containers:
```yaml
          resources:
            limits:
              cpu: 2
              memory: "12G"
            requests:
              cpu: 1
              memory: "8G"
```

I'm getting the following validation error:
```
./bin/linux/amd64/kubeval ec.10395.yaml 
The document ec.10395.yaml contains an invalid Job
---> spec.template.spec.containers.0.resources.requests: Invalid type. Expected: [string,null], given: integer
---> spec.template.spec.containers.0.resources.limits: Invalid type. Expected: [string,null], given: integer
```

The error doesn't refer to the cpu key for some reason. Furthermore, kubectl happily creates my job correctly and the documentation itself uses an integer for cpus as well as values like "200m".

**Comment by garethr** [comment]
So, according to the specification this is actually doing the right thing. However Kubernetes doesn't use quite the same rules internally so `kubeval` is finding a bunch of similar issues. I'll open upstream bugs when I get a moment and also talk to SIG API Machinery about the actual internal implementation so I can have `kubeval` do the right thing.

From the upstream OpenAPI description at https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json

```
io.k8s.api.core.v1.ResourceRequirements: {
  description: "ResourceRequirements describes the compute resource requirements.",
  properties: {
    limits: {
      description: "Limits describes the maximum amount of compute resources allowed. More info: 
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/",
      type: "object",
      additionalProperties: {
        $ref: "#/definitions/io.k8s.apimachinery.pkg.api.resource.Quantity"
      }
    },
    requests: {
      description: "Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/",
      type: "object",
      additionalProperties: {
        $ref: "#/definitions/io.k8s.apimachinery.pkg.api.resource.Quantity"
      }
    }
  }
},
```

Note that cpu and memory are not explicitly defined, but resources can take additional properties as long as they are of type quantity. Quantity is defined as:

```
io.k8s.apimachinery.pkg.api.resource.Quantity: {
  type: "string"
},
```


So:
* the error appears at the limit and request key because they are additional properties. I'll see if the actual key is available from the json schema Go library, or file a bug for that
* the spec actually says this should be a string. If you try with "200m" I think it will work for instance.
* Kubernetes accepts null to mean blank string, hence the `[string,null]` part of the error which kubeval adds in

**Comment by garethr** [comment]
Posted a clarifying question to SIG API Machinery at https://groups.google.com/forum/#!topic/kubernetes-sig-api-machinery/dLCXrZRwWpU

**Comment by garethr** [comment]
> This is not really a bug. It's a convenience feature specific to Quantity

I'll update the upstream specs to allow Quantity to be a number.

**Comment by garethr** [comment]
This should now work as expected. Tests in https://github.com/garethr/kubeval/commit/06e025e68cb11683bbf5ac968c552f5af4ed9a23

The fix is in the upstream schemas in https://github.com/garethr/kubeval/commit/06e025e68cb11683bbf5ac968c552f5af4ed9a23 so should work without needing you to update kubeval.

**Comment by garethr** [comment]
I've also opened an upstream bug to track a fix in this spec https://github.com/kubernetes/kubernetes/issues/50957

**Comment by thedrow** [comment]
Wonderful! Thank you very much.
