### ISSUE TITLE
No support for a list of specifications

### ISSUE THREAD

**Issue by wzhliang** [garethr/kubeval#58]
I've try to run `kubeval` with a simple `kubeval xxx.yaml` and go the following error:

> 1 error occurred:
> 
> * Problem loading schema from the network at https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/master-standalone/list.json: Could not read schema from HTTP, response status is 404 Not Found

wget confirms that it's not there

**Comment by wzhliang** [comment]
I looked around and this is actually because the YAML file I sent to `kubeval` is of type `List` and the corresponding JSON file isn't there. I guess this is not a valid use case?

**Comment by garethr** [comment]
I'll close this issue in favour of https://github.com/garethr/kubeval/issues/33 which is the same think and has a bit more details. 

List isn't an object in the OpenAPI description, which is why this is occurring. If you have links to the documentation around `list` that would be appreciated. I've not had chance to look into that yet but having more details would be useful to determine whether this wants a fix in `kubeval` or reporting upstream as a bug in the OpenAPI description generator.
